= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.3.3...v0.3.4++[0.3.4^] (2021-01-14)

=== Bug Fixes

* *_mapdata:* ensure map data is directly under `values`
(https://github.com/saltstack-formulas/powerdns-formula/commit/fcc7200d21524f8e334256b8855bdc5aef258601[fcc7200^])

=== Tests

* *_mapdata:* update for `_mapdata/init.sls` change
(https://github.com/saltstack-formulas/powerdns-formula/commit/bf577521aec4b48058a2c7901fd8081de7e21711[bf57752^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.3.2...v0.3.3++[0.3.3^] (2020-12-27)

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/56c2c485e5b0d221f39ec62539f876fba16ffa47[56c2c48^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/8577924fff419acf9d8410c8fd3f581a2b0fceef[8577924^])

=== Tests

* *_mapdata:* generate verification files
(https://github.com/saltstack-formulas/powerdns-formula/commit/99257e551c122986e616fae6161461c4e0e056f1[99257e5^])
* *map:* verify `map.jinja` dump using `_mapdata` state
(https://github.com/saltstack-formulas/powerdns-formula/commit/4279f0498d1449087bc41d0b2d64d70ff8fa657d[4279f04^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.3.1...v0.3.2++[0.3.2^] (2020-12-16)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/7a19c6771b7fa445a4fae663bb31e6476d00684e[7a19c67^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/powerdns-formula/commit/39907b66634e0a6ca8d08b8660086df3e74b9c9b[39907b6^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/0bb19ea640db71afc96eed7afdd5899192303faf[0bb19ea^])
* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/2071a523aef48437b4bb2defea96264f439d70b5[2071a52^])
* *kitchen+travis:* adjust matrix to add `3000.2` & remove `2018.3`
 [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/61f4f47e9d548bfba5d3a584bb499d04f5008214[61f4f47^])
* *kitchen+travis:* adjust matrix to add `3000.3` [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/ab1b2c78ed320922460b6a153bd8ac353f2f1f1d[ab1b2c7^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/c223812b9a1ff23f430c986520041b553fd182cc[c223812^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/3aec1f44abd6a562d78c16ee3cf5809b3244fa1d[3aec1f4^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/b712795181c7f9ff38e3ddc1608e10e2d3960823[b712795^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/5e79467db0ed3f36f4a8c605f4703a9fe46c9da5[5e79467^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/2cf5ed91d1927ebb884592bdcf5ae108b02edbfb[2cf5ed9^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/058986d9dfd3ab37fd46fb88529ccfc2ee0652ce[058986d^])

=== Documentation

* *readme:* use correct heading [skip ci]
(https://github.com/saltstack-formulas/powerdns-formula/commit/b2bcbfb44c4b0eb0b95a863b8984f69604c78a79[b2bcbfb^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.3.0...v0.3.1++[0.3.1^] (2020-04-18)

=== Bug Fixes

* modify to get working on `debian`, `fedora` & `opensuse-leap`
(https://github.com/saltstack-formulas/powerdns-formula/commit/0b130f0deb8bffcbaccd3d5b8959a0d026d5cc38[0b130f0^])

=== Continuous Integration

* *kitchen+travis+inspec:* add initial platforms and test structure
(https://github.com/saltstack-formulas/powerdns-formula/commit/0b2180a183d0f2326e6811a1dadac93f394adfb2[0b2180a^])

=== Documentation

* *readme:* update `Testing` section
(https://github.com/saltstack-formulas/powerdns-formula/commit/47232be82a3b7ebfb00872435ca76a2d4bd460a5[47232be^])

=== Tests

* *inspec:* add tests
(https://github.com/saltstack-formulas/powerdns-formula/commit/45d97d329247aa2e5b86ac7988cd94bbac2dc495[45d97d3^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.2.2...v0.3.0++[0.3.0^] (2020-04-17)

=== Bug Fixes

* *watchin:* fix missing `watch_in`s on `powerdns` service
(https://github.com/saltstack-formulas/powerdns-formula/commit/38fa08b2fb71fb6e16234af3387a5dce90aa787d[38fa08b^])

=== Features

* *ldap:* add LDAP Backend support
(https://github.com/saltstack-formulas/powerdns-formula/commit/3dc06757bde1ae15898b370381abf4030c93ddb0[3dc0675^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.2.1...v0.2.2++[0.2.2^] (2020-04-17)

=== Bug Fixes

* *conf-owner:* put `user` and `group` of `pdns` service in `map.jinja`
(https://github.com/saltstack-formulas/powerdns-formula/commit/c8a2c0d1219342e0d92bab3732db0b4b6222b607[c8a2c0d^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.2.0...v0.2.1++[0.2.1^] (2020-04-17)

=== Code Refactoring

* *map:* use `map.jinja` ng
(https://github.com/saltstack-formulas/powerdns-formula/commit/4303ab30f9bd0fca521dd0d476cc5ac6150fcd71[4303ab3^])

== link:++https://github.com/saltstack-formulas/powerdns-formula/compare/v0.1.0...v0.2.0++[0.2.0^] (2020-04-17)

=== Bug Fixes

* *salt-lint:* fix error
(https://github.com/saltstack-formulas/powerdns-formula/commit/c1634497f5f9de86824a4db60474e5bea43429c2[c163449^])
* *yamllint:* fix error
(https://github.com/saltstack-formulas/powerdns-formula/commit/12033155a82105e022bf06f34cdd4688a61abdd3[1203315^])

=== Documentation

* *readme:* standardise structure (without testing section)
(https://github.com/saltstack-formulas/powerdns-formula/commit/1f2467627ced5f414cbadbad9c279d74d38772b6[1f24676^])

=== Features

* *semantic-release:* implement for this formula (without platforms)
(https://github.com/saltstack-formulas/powerdns-formula/commit/e0ce7550aa98b11470746a36e508658ff7ceec2b[e0ce755^])
